language: node_js

sudo: false

node_js:
  - "10"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

notifications:
  email: false

script:
  - npm run docs
  
after_success:
  - bash ./scripts/deploy.sh

env:
  global:
    - GH_USER: itcast-hsian
    - GH_REF: hm-libraries
    - DIST: lib